version: "3.7"

services:
  backend-service:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
      - $GOPATH/bin/:/usr/local/bin
    ports:
      - '8081:8080'
    command: go run .

  frontend-service:
    build: ./frontend
    ports:
      - '8082:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-service
