version: "3.7"

services:
  backend-service:
    build: ./backend
    ports:
      - '8081:8080'
    restart: always

  frontend-service:
    build: ./frontend
    ports:
      - '8082:80'
    depends_on:
      - backend-service